### ISSUE TITLE
fg = ifm3dpy.FrameGrabber(cam, ifm3dpy.IMG_AMP | ifm3dpy.INV_INTR_CAL) have error 

### ISSUE THREAD

**Issue by PHILCHEN666** [ifm/ifm3d#330] opened 2021-10-31 03:36 UTC
now,i have the ifm3dpy,it can run in the linux 20.04 focal,In the VMware,i also can get data from (ping 192.168.0.69),it show we already connect to the camera,i try the code you submit in github "example code" in image_rectification/python/  . but error in "fg = ifm3dpy.FrameGrabber(cam, ifm3dpy.IMG_AMP | ifm3dpy.INV_INTR_CAL) RuntimeError: Unknown error -1000019",if i change it to fg = ifm3dpy.FrameGrabber(cam). it also have error happen. numpy.linalg.LinAlgError: Singular matrix".how could i slove this problem,thanks for your patient guidance.The camera i use is TOF O3D303,

**Comment by lola-masson** [comment] 2021-11-01 12:11
You might need to update your firmware. Which version is currently on your O3D303?

**Comment by PHILCHEN666** [comment] 2021-11-01 14:52
ifm_VisionAssistant show the Firmware ver 1.6.2114

**Comment by lola-masson** [comment] 2021-11-01 15:10
You can download the new FW (we are at version 1.71.x) on [ifm.com](https://www.ifm.com/us/en/product/O3D303?tab=documents). You will need to create a (free) account. Please update your O3D and check if you have the same problem as before.

**Comment by PHILCHEN666** [comment] 2021-11-02 05:14
thank you ,it can work now

**Comment by PHILCHEN666** [comment] 2021-11-03 02:23
hello, i want know the xyz_image capture by the ifm3dpy. the value in that image not the float (for example -1.351,2.31 etc),but is (-652,256),what the relationship about the value in real x distance and the image value.same question in amp_image,rdis_image,yz_image.

**Comment by graugans** [comment] 2021-11-04 07:30
Hey @PHILCHEN666 did I get you right, the issue is solved? In this case please close this issue as-well.

**Closed** 2021-11-05 08:32 UTC
Labels: question
