### ISSUE TITLE
Problem with Ip

### ISSUE THREAD

**Issue by matteofiorini** [ifm/ifm3d#165] opened 2019-07-24 09:05 UTC
Hi, I just installed ifm3d but I am having issues about the connection with the camera. I already tried in windows without any problem. 
The IP of my camera is 169.254.89.234 and since it is different from the normal one I cannot connect it. I already followed the troubleshoot guide in particular I run these commands:

matteo@matteo-MS-7A37:~$ ifm3d --ip=169.254.89.234 ls
ifm3d error: -100001
Lib: XMLRPC Timeout - can you `ping' the sensor?
matteo@matteo-MS-7A37:~$ IFM3D_IP=169.254.89.234 ifm3d ls 
ifm3d error: -100001
Lib: XMLRPC Timeout - can you `ping' the sensor?
matteo@matteo-MS-7A37:~$ ping 169.254.89.234PING 169.254.89.234 (169.254.89.234) 56(84) bytes of data.
64 bytes from 169.254.89.234: icmp_seq=1 ttl=64 time=0.033 ms
64 bytes from 169.254.89.234: icmp_seq=2 ttl=64 time=0.024 ms
64 bytes from 169.254.89.234: icmp_seq=3 ttl=64 time=0.025 ms
^C
--- 169.254.89.234 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2049ms
rtt min/avg/max/mdev = 0.024/0.027/0.033/0.005 ms

So it seems that ifm3d cannot connect to the camera even if I can ping it and change the ip address to the address that I can ping. 
Thanks for the help.

**Comment by tpanzarella** [comment] 2019-07-26 13:35
Closing. This is a duplicate of #166

**Closed by tpanzarella** 2019-07-26 13:35 UTC
